// Auto-generated by scripts/deploy.js
const CONTRACT_ADDRESS = "0x853B02ABE18778AFd3166aFAba85BE574856b7c0";
// dia chi vi sau khi deploy len.
const CONTRACT_ABI = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "recordId",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "cid",
        type: "string",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "patientKey",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "doctor",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "RecordAdded",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_recordId",
        type: "string",
      },
      {
        internalType: "string",
        name: "_cid",
        type: "string",
      },
      {
        internalType: "bytes32",
        name: "_patientKey",
        type: "bytes32",
      },
    ],
    name: "storeRecord",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_recordId",
        type: "string",
      },
    ],
    name: "verifyRecord",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_patientKey",
        type: "bytes32",
      },
    ],
    name: "getPatientRecords",
    outputs: [
      {
        internalType: "string[]",
        name: "",
        type: "string[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
// sau khi deploy len đoạn code này sẽ tự động được ghi đè bởi địa chỉ và ABI của hợp đồng đã deploy.
module.exports = { CONTRACT_ADDRESS, CONTRACT_ABI };
